name: Deploy to VM

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
   test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-staging:
    needs: test
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment_name: staging
      target_folder: staging
      service_name: app-staging
      health_port: "3001"
    secrets:
      vm_host: ${{ secrets.VM_HOST }}
      vm_username: ${{ secrets.VM_USER }}
      vm_ssh_key: ${{ secrets.VM_SSH_KEY }}

  deploy-production:
    needs: deploy-staging
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment_name: production
      target_folder: production
      service_name: app-production
      health_port: "3000"
    secrets:
      vm_host: ${{ secrets.VM_HOST }}
      vm_username: ${{ secrets.VM_USER }}
      vm_ssh_key: ${{ secrets.VM_SSH_KEY }}
