name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      target_folder:
        required: true
        type: string
      service_name:
        required: true
        type: string
      health_port:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.environment_name }}
    steps:
      - name: Deploy and restart
        run: |
          cd /home/ubuntu/apps/${{ inputs.target_folder }}
          rm -rf temp
          git clone https://github.com/2973tok/github-actions.git temp
          cp temp/server.js .
          cp temp/package.json .
          rm -rf temp
          npm install
          sudo systemctl restart ${{ inputs.service_name }}
          sleep 2
          curl -f http://localhost:${{ inputs.health_port }}/health || exit 1}
