name: Merhaba Dünya

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selamla:
    runs-on: ubuntu-latest
    steps:
      - name: Bir mesaj yazdır
        run: echo "Bu ikinci denemem!"

      - name: Tarihi göster
        run: date

      - name: Klasörü listele
        run: ls -la
